name: Assign Issue

on:
  issues:
    types: [opened]

jobs:
  assign_issue:
    runs-on: ubuntu-latest

    steps:
      - name: 'am2024024'
        uses: peter-evans/assign-issue@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          assignees: 'am20242024'  # Replace 'X' with the GitHub username of the team member
