name: Run Tests on PR Merge

on:
  push:
    branches:
      - main  # Trigger the workflow when a push is made to the main branch (e.g., PR merge)

jobs:
  test:
    runs-on: ubuntu-latest  # Use an Ubuntu runner (you can change this if needed)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the appropriate Python version (e.g., 3.8 or 3.9)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assumes dependencies are listed in requirements.txt

      - name: Run tests with pytest
        run: |
          pytest  # Run tests using pytest
